version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-result
    environment:
      MYSQL_ROOT_PASSWORD: mySQL@abc
      MYSQL_DATABASE: resultservice
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  question-service:
    image: resultservice
    container_name: resultservice
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/resultservice?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mySQL@abc
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
